version: 1
disable_existing_loggers: False
formatters:
  simple:
      format: "%(asctime)s - %(pathname)s:%(lineno)d - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: debug.log
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, file_handler]