{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "disable_existing_loggers": {
      "type": "boolean"
    },
    "formatters": {
      "type": "object",
      "properties": {
        "simple": {
          "type": "object",
          "properties": {
            "format": {
              "type": "string"
            }
          },
        }
      },
    },
    "handlers": {
      "type": "object",
      "properties": {
        "console": {
          "type": "object",
          "properties": {
            "class": {
              "type": "string"
            },
            "level": {
              "type": "string"
            },
            "formatter": {
              "type": "string"
            },
            "stream": {
              "type": "string"
            }
          },
          "required": ["class", "level", "formatter", "stream"]
        },
        "file_handler": {
          "type": "object",
          "properties": {
            "class": {
              "type": "string"
            },
            "level": {
              "type": "string"
            },
            "formatter": {
              "type": "string"
            },
            "filename": {
              "type": "string"
            },
            "encoding": {
              "type": "string"
            }
          },
          "required": ["class", "level", "formatter", "filename"]
        }
      },
      "required": ["file_handler"]
    },
    "root": {
      "type": "object",
      "properties": {
        "level": {
          "type": "string"
        },
        "handlers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["level", "handlers"]
    }
  },
  "required": ["version", "formatters", "handlers", "root"]
}