workflow_name: "dna_visualization"
workflow_version: "0.0.2"
iam_policy_file: "iam_policy.json"
home_region:
  provider: "gcp"
  region: "us-east1"
estimated_invocations_per_month: 1000000
constraints:
  hard_resource_constraints:
    cost: null
    runtime: null
    carbon: null
  soft_resource_constraints:
    cost: null
    runtime: null
    carbon: null
  priority_order:
    - carbon
    - cost
    - runtime
regions_and_providers:
  allowed_regions:
    - provider: "gcp"
      region: "us-east1"
    - provider: "gcp"
      region: "us-west1"
    - provider: "gcp"
      region: "us-west2"
    - provider: "gcp"
      region: "northamerica-northeast1"
  disallowed_regions:
  providers:
    gcp:
      config:
        timeout: 300
        memory: 1024
